### ISSUE TITLE
Se me encomienda hacer el Login y el Registro para operarios

### ISSUE THREAD

**Issue by adrycarou896** [Arquisoft/InciDashboard_e5b#12]

**Comment by adrycarou896** [comment]
En principio ya estaría.

**Comment by adrycarou896** [comment]
Hay que mejorar el login y el registro para que puedan hacer estas funciones todo tipo de usuarios (no solo operarios)

**Comment by CarlosSanabriaM** [comment]
Ahora como sabemos que las 4 aplicaciones van por separado, ya no es necesario que se puedan registrar/iniciar sesión más tipos de usuario.
El login y signup está, por tanto, revisado y terminado.
